
kind: ServiceAccount
apiVersion: v1
metadata:
  name: tester
  namespace: default

---

kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: discovery-assistant
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]
    
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: discovery-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: tester
    apiGroup: ""
roleRef:
  kind: Role
  name: discovery-assistant
  apiGroup: ""

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: cluster-discovery-assistant
rules:
  - apiGroups: [""]
    resources: ["configmaps", "pods", "services", "endpoints", "secrets"]
    verbs: ["get", "list", "watch"]

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cluster-discovery-binding
subjects:
  - kind: ServiceAccount
    name: tester
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: cluster-discovery-assistant
  apiGroup: ""