server:
  port: 8080

debug: info

spring:
  cloud:
    kubernetes:
      # reload:
      #   enabled: true
      discovery:
        enabled: true
        all-namespaces: false

eureka:
  client:
    # serviceUrl:
    #   defaultZone: ${EUREKA_SERVER_ADDRESS}
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS